// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'package:photon/src/photon_component.dart' as prefix1;
import 'package:photon/src/photon_reflector.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_builder_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"Component",
            r".Component",
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 3, 7, 8, 9],
            const <int>[10, 11, 12, 13, 14, 2, 3, 4, 7, 8],
            const <int>[5, 6],
            -1,
            {r"name": () => prefix1.Component.name},
            {r"name=": (value) => prefix1.Component.name = value},
            {r"": (b) => () => b ? new prefix1.Component() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        new r.VariableMirrorImpl(r"childComponents", 2130949, 0,
            const prefix0.Reflector(), -1, -1, -1, null, null),
        new r.VariableMirrorImpl(r"name", 32789, 0, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        new r.MethodMirrorImpl(r"render", 262146, 0, null, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"rerender", 262146, 0, null, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, -1, -1, 4),
        new r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, -1, -1, 5),
        new r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 1, -1, -1, 6),
        new r.MethodMirrorImpl(r"el", 131075, 0, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"template", 65539, 0, null, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"", 0, 0, -1, -1, -1, null, const <int>[],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"==", 131074, null, -1, -1, -1, null,
            const <int>[1], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"toString", 131074, null, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, -1, -1, null,
            const <int>[2], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null)
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(r"_name", 32870, 6, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"other", 16390, 10,
            const prefix0.Reflector(), null, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"invocation", 32774, 12,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null)
      ],
      <Type>[prefix1.Component],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"render": (dynamic instance) => instance.render,
        r"rerender": (dynamic instance) => instance.rerender,
        r"childComponents": (dynamic instance) => instance.childComponents,
        r"el": (dynamic instance) => instance.el,
        r"template": (dynamic instance) => instance.template
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
